name: Lint

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
