name: Documentation

# This GitHub Action sets up a workflow to generate and deploy documentation.
# It triggers on pushes to specific branches and pull requests to master and
# staging branches. It runs on the latest version of Ubuntu. The deploy job
# checks out the code, uses the andstor/jsdoc-action@v1 action to generate
# documentation using JSDoc, and then deploys the documentation using the
# peaceiris/actions-gh-pages@v3 action.

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./out
          recurse: true
          config_file: jsdoc.json
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
